### ISSUE TITLE
Content provider crashes without reading level

### ISSUE THREAD

**Issue by gscdev** [elimu-ai/content-provider#71]
Converting StoryBooks without readingLevel:

```
java.lang.NullPointerException: name == null
    at java.lang.Enum.valueOf(Enum.java:242)
    at ai.elimu.model.enums.ReadingLevel.valueOf(ReadingLevel.java:6)
    at ai.elimu.content_provider.utils.converter.CursorToStoryBookGsonConverter.getStoryBookGson(CursorToStoryBookGsonConverter.java:39)
    at ai.elimu.content_provider.utils.ContentProviderHelper.getStoryBookGsons(ContentProviderHelper.java:191)
```

**Comment by nya-elimuai** [comment]
@gscdev Updated the Vitabu app with a new version of the content-provider library here: https://github.com/elimu-ai/vitabu/commit/729402bb5cf48e398185bbfbd53ebf620edffcc8
