### ISSUE TITLE
Audio download fails in test environment

### ISSUE THREAD

**Issue by nya-elimu** [elimu-ai/content-provider#83]
**Describe the bug**
When downloading audios, the app fails:
```
2021-09-02 10:48:38.701 14416-14849/ai.elimu.content_provider.debug I/ai.elimu.content_provider.util.MultimediaDownloader: Downloading from http://hin.test.elimu.ai/audio/44_r1.mp3
2021-09-02 10:48:38.804 14416-14849/ai.elimu.content_provider.debug I/ai.elimu.content_provider.util.MultimediaDownloader: responseCode: 200
2021-09-02 10:48:38.829 14416-14849/ai.elimu.content_provider.debug E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: ai.elimu.content_provider.debug, PID: 14416
    java.lang.NoSuchMethodError: No static method withInitial(Ljava/util/function/Supplier;)Ljava/lang/ThreadLocal; in class Ljava/lang/ThreadLocal; or its super classes (declaration of 'java.lang.ThreadLocal' appears in /system/framework/core-oj.jar)
        at org.apache.commons.io.IOUtils.<clinit>(IOUtils.java:183)
        at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:2400)
        at ai.elimu.content_provider.util.MultimediaDownloader.downloadFileBytes(MultimediaDownloader.java:35)
```

**To Reproduce**
Install the `debug` or `qa_test` build variant of the app, and select Hindi as the preferred language.

1. Go to the menu drawer
2. Click on "Audios"
3. See error in the app's log output

**Expected behavior**
Audios should download. However, the app crashes.

**Screenshots**
![device-2021-09-02-110300](https://user-images.githubusercontent.com/15718174/131806230-fec0045d-ac9e-4758-a1af-0a6a85fd366b.png)

**Device information (please complete the following information):**
 - Device type: Tablet
 - Device brand: Huawei
 - Android version: 7.0

**Comment by jo-elimu** [comment]
https://github.com/elimu-ai/content-provider/issues/161
